### ISSUE TITLE
Suggest using keyword args for parameters by default

### ISSUE THREAD

**Issue by dieggsy** [Tevo45/juniper#3]
If an API call has a lot of parameters, it can be tough to know what goes where (especially for automatically generated code) - it'd be nice if we could label the args using keywords instead.

**Comment by Tevo45** [comment]
Hmm, we already present optional parameters as keyword by default; having required parameters as keyword by default doesn't feel right, but I suppose it should be doable to add a switch to the generator, so you could `(juniper:bindings-from-url "https://esi.evetech.net/_latest/swagger.json" :required-as-keyword t)` and have all parameters being keyword in cases where it would be helpful.

**Comment by Tevo45** [comment]
I've added an optional :required-as-keyword to the generator macros that turns all parameters into keyword in 9ba8e87; generated code seems fine but haven't done much testing, please let me know what you think.

**Comment by dieggsy** [comment]
Perhaps you're right, but in any case, that's awesome, thanks for that!

**Comment by dieggsy** [comment]
It occurs to me that having required parameters as keyword by default is somehow more similar to an actual web request, where you explicitly name the parameters anyway, one way or another...
